import { CrossStackScanner, ScanResult, ScanOptions } from "../types";
import { heading, joinSections, bold } from "../../utils/markdown";

// Short human descriptions for known generated files. Anything not in this
// map falls through with a generic label.
const FILE_DESCRIPTIONS: Record<string, string> = {
  "overview.md": "Architecture summary — read this first",
  "api-contract.md": "Backend ↔ mobile endpoint alignment (matched + orphan routes)",
  "deps.md": "Dependencies, grouped by category",
  "flutter-deps.md": "Flutter dependencies from pubspec.yaml",
  "express-deps.md": "Express dependencies from package.json",
  "routes.md": "All backend API routes with mount prefixes + middlewares",
  "middleware.md": "Global Express middleware chain",
  "schema.md": "Database schema (Prisma / Drizzle / Mongoose / TypeORM)",
  "services.md": "Backend service/controller layer — signatures only",
  "config.md": "Environment variables (from .env.example + code scan)",
  "screens.md": "Mobile screens + routing (GoRouter / AutoRoute / manual)",
  "state.md": "State management (Riverpod / Bloc / GetX / Provider / MobX)",
  "components.md": "Reusable Flutter widgets with constructor signatures",
  "models.md": "Flutter data models + serialization approach",
  "api-client.md": "HTTP calls made by the Flutter app",
  "nextjs-deps.md": "Next.js dependencies from package.json",
  "layouts.md": "Next.js layouts and special files (loading/error/not-found) per route segment",
  "server-actions.md": "Next.js server actions ('use server' exported functions)",
  "exports.md": "Package public entry points (exports/main/types/bin)",
  "types.md": "Exported types, interfaces, and enums",
  "api.md": "Public API surface — exported functions and classes",
};

function describe(filename: string): string {
  if (FILE_DESCRIPTIONS[filename]) return FILE_DESCRIPTIONS[filename];
  // Strip framework prefix and try again
  const stripped = filename.replace(/^(flutter|express|nextjs|bun|typescript)-/, "");
  if (FILE_DESCRIPTIONS[stripped]) return FILE_DESCRIPTIONS[stripped];
  return "Generated index file";
}

export const instructionsScanner: CrossStackScanner = {
  name: "instructions",

  async scan(
    allResults: ScanResult[],
    frameworks: string[],
    _options: ScanOptions,
  ): Promise<ScanResult | null> {
    if (allResults.length === 0) return null;

    const fileLines = allResults
      .map((r) => r.filename)
      .sort()
      .map((f) => `- \`.stack-shared-ai/${f}\` — ${describe(f)}`);

    const body = [
      heading(1, "Codebase Index — AI Assistant Instructions"),
      `This project uses ${bold("stack-shared-ai")} to pre-generate compact index files describing the codebase. ${bold("Read these files before exploring source code")} — they are designed to answer most structural questions in a fraction of the tokens.`,
      `${bold("Frameworks detected")}: ${frameworks.join(", ")}`,
      joinSections(heading(2, "Available Index Files"), fileLines.join("\n")),
      joinSections(
        heading(2, "Suggested Reading Order"),
        [
          "1. `overview.md` — project shape at a glance",
          "2. `api-contract.md` (if present) — how mobile and backend line up",
          "3. Domain-specific files relevant to the task (routes, schema, screens, state, etc.)",
          "4. Only then open actual source files for the specific functions involved",
        ].join("\n"),
      ),
      joinSections(
        heading(2, "Regenerating"),
        "These files are generated by `npx stack-shared-ai`. Re-run after significant code changes. They are safe to commit.",
      ),
    ];

    return {
      filename: "INSTRUCTIONS.md",
      content: body.join("\n\n") + "\n",
    };
  },
};
